---
- hosts: localhost
  become: yes
  tasks:  
  - name: install apache
    apt:
      name: apache2
      state: absent
  - name: start service
    service:
      name: apache2
      state: started 
