Install LAMP on Centos
1. sudo yum install httpd
2. sudo systemctl start httpd.service
3. sudo yum install php php-mysql
4. sudo systemctl restart httpd.service
---
# Installing LAMP on Centos7
---
- hosts: all
  become: yes
  tasks:
  - name: Install httpd 
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      enabled: yes
      state: started
  - name: Install PHP packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
  - name: Restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted

