# Installing LAMP on Ubuntu 18.04
---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: Restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: Install PHP packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
  - name: Restart apache after php
    service:
      name: apache2
      enabled: yes
      state: restarted
