# Installing LAMP on Ubuntu 18.04
---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes
    notify:
      - restart apache 
    when: ansible_os_family == "Debian" 
  - name: Install PHP packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
    notify:
      - restart apache 
    when: ansible_os_family == "Debian" 
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian" 
