# Installing LAMP on Ubuntu 18.04 & Redhat
---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes
    notify:
      - restart apache 
    when: ansible_os_family == "Debian" 
  - name: Install httpd
    yum:
      name: httpd
      state: present
    notify:
      - restart httpd
    when: ansible_os_family == "RedHat"
  - name: Install PHP packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
    notify:
      - restart apache 
    when: ansible_os_family == "Debian" 
  - name: Install PHP packages on redhat
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-mbstring
    notify:
      - restart httpd
    when: ansible_os_family == "RedHat"
  - name: download php web page
    get_url:
      url: https://raw.githubusercontent.com/venkateshyadavali/Ansible/master/lamp/info.php
      dest: /var/www/html/info.php
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian" 
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: started
