# Installing LAMP on Ubuntu 18.04 & Redhat using package
---
- hosts: all
  become: yes
  vars:
  - pack_name: nginx
  - php_packages:
    - php
    - php-mysql
  tasks:
  - name: Install Apache
    package:
      name: "{{ pack_name }}" 
      state: present
    notify:
      - restart apache 
  - name: Install PHP packages and utilities
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ php_packages }}"
    notify:
      - restart apache
  - name: download php web page
    get_url:
      url: https://raw.githubusercontent.com/venkateshyadavali/Ansible/master/lamp/info.php
      dest: /var/www/html/info.php
    notify:
      - restart apache
  handlers:
  - name: restart apache
    service:
      name: "{{ pack_name }}"
      enabled: yes
      state: restarted
