---
- hosts: all
  become: yes
  tasks:
  - name: Install tomcat7
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
      - restart apache
  - name: Copy the application file
    get_url:
      url: https://raw.githubusercontent.com/venkateshyadavali/Ansible/master/lamp/info.php
      dest: /var/www/html/info.php
    notify:
      - restart apache
- handlers:
  - name: restart apache
    service: apache2
    state: restarted
